---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maxy.
--- DateTime: 2021/1/18 11:27
---


local result = {}
local values = redis.call('ZRANGEBYSCORE', KEYS[1], ARGV[1], ARGV[2], ARGV[3], ARGV[4], ARGV[5])
if (#values > 0) then
    for i, v in ipairs(values) do
        local value = redis.call('LPUSH', KEYS[2], v)
        if (value) then
            redis.call('ZREM', KEYS[1], v)
        end
    end
    result[1] = values;
end
return result







