---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maxuyang.
--- DateTime: 2021/1/18 11:27
---

local result = {}
local list = redis.call('LRANGE', KEYS[1], 0, ARGV[1])
result[1] = #list
for i, key in pairs(list) do
    local groupName = redis.call('RPOPLPUSH', list, KEY[1], '_backup')
    table.insert(result, i + 1, groupName)
end
return result